backend:
  name: github
  repo: LimeWub/components-test
  branch: main # Branch to update (optional; defaults to master)
  # base_url: https://components-test.vercel.app/ #Change to EXACT match for deployment url
  base_url: http://localhost:3000/ #Change to EXACT match for deployment url
  api_root: https://api.github.com # Shouldn't be necessary
  auth_endpoint: api/auth

local_backend: true

# publish_mode: editorial_workflow

media_folder: "public/admin/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: static
    label: "Static Pages"
    files:
      - label: "Landing Page"
        name: landing
        file: "content/landing/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Tabs"
            name: "tabs"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "Content",
                  name: "content",
                  widget: "markdown",
                  sanitize_preview: true,
                } # editor_components (custom: Colours, Shadows, Icons, Space, etc., Api Ref)

  - name: dynamic
    label: "Dynamic Pages"
    folder: "content"
    create: true
    identifier_field: slug
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Links",
          name: "links",
          widget: "object",
          collapsed: true,
          fields:
            [
              {
                label: "View source",
                name: "viewSource",
                widget: "string",
                required: false,
              },
              {
                label: 'Show "Report An Issue"',
                name: "showReportAnIssue",
                widget: "boolean",
                required: false,
              },
              {
                label: "Custom Links",
                name: "custom",
                widget: "list",
                summary: "{{fields.name}}",
                required: false,
                fields:
                  [
                    { label: "Name", name: "name", widget: "string" },
                    { label: "href", name: "href", widget: "string" },
                    {
                      label: "Is External",
                      name: "isExternal",
                      widget: "boolean",
                    },
                  ],
              },
            ],
        }
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        summary: "{{fields.title}}"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Content",
              name: "content",
              widget: "markdown",
              sanitize_preview: true,
            }
      - {
          label: "Parent",
          name: "parent",
          widget: "relation",
          collection: "dynamic",
          value_field: "{{uuid}}",
          search_fields: ["title"],
          display_fields: ["{{title}} --- {{nestedSlug}}"],
          required: false,
          multiple: false,
        }
      - { label: "UUID", name: "uuid", widget: "uuid" }
