name: auto-fix

on:
  push:
    branches:
      - 'main'

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: apply auto-fix changes'
