name: auto-fix

on:
  push:
    branches:
      - 'main'

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Generate restricted GH API token for Atom CI app
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.ATOM_CI_APP_ID }}
          private_key: ${{ secrets.ATOM_CI_APP_PRIVATE_KEY }}

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Setup environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '20.11'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint (Library)
        working-directory: lib
        run: yarn lint

      - name: Run Prettier (Library)
        working-directory: lib
        run: yarn format

      - name: Run Prettier (Documentation)
        working-directory: documentation
        run: yarn format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: 'atom-ci-actions[bot]'
          commit_user_email: '129779914+atom-ci-actions[bot]@users.noreply.github.com'
          commit_message: 'chore: apply auto-fix changes'
