name: auto-fix

on:
  pull_request:
    branches:
      - 'main'

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'

      - run: yarn install

      - name: Run ESLint
        run: yarn lint && yarn format

      - name: Run Prettier
        run: yarn format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply auto-fix changes
