name: Test & validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'

      - run: yarn install

      - name: Test
        run: yarn test

      - name: Validate
        run: yarn validate
  publish:
    name: publish
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - run: yarn install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.0
        with:
          branch: 'main'
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          dry_run: true # temporary! 
            
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_WITHOUT_THIS_SUFFIX }}
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
