name: Test & validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'

      - run: yarn install

      - name: Test
        run: yarn test

      - name: Validate
        run: yarn validate
  publish:
    name: publish
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - run: yarn install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.0
        id: semantic # Need an `id` to refer back to this step from the next one
        with:
          branch: 'main'

        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Log new version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo ${{ steps.semantic.outputs.new_release_version }}
