name: Visual Regression

on:
  push:
    branches: -main
  pull_request:
    branches: -main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

permissions:
  actions: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Print stuff
        run: |
          echo ${{ github.ref }}
          echo ${{ contains(github.event.pull_request.labels.*.name, 'visual-regression') }}

  visual-regression:
    if: ${{ github.ref == 'main' && true || contains(github.event.pull_request.labels.*.name, 'visual-regression') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '20.11'

      - name: Install Dependencies
        run: yarn install

      - name: Build Library
        run: yarn build:lib

      - name: Build Documentation
        run: yarn build:docs

      - name: Start Web Server as a Daemon
        run: |
          yarn start:docs &
          disown -h %1

      - name: Install Playwright browsers + dependencies
        run: yarn playwright install --with-deps

      - name: Run Visual Regression
        run: yarn vr:chromium
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
